'use client';

import { ArrowDownRight, ArrowRight, CalendarDays, Camera, Check, ChevronLeft, ChevronRight, Clock3, MapPin, Menu, MessageCircle, Phone, Sparkles, Star, X } from 'lucide-react';
import { useMemo, useState } from 'react';

const INSTAGRAM = 'https://www.instagram.com/johnny_cutzznlocks?igsi=NWs5aGVzM2E4ajc3';
const images = ['/portfolio/work-01.jpg','/portfolio/work-02.jpg','/portfolio/work-03.jpg','/portfolio/work-04.webp','/portfolio/work-05.jpg','/portfolio/work-06.jpg','/portfolio/work-07.jpg','/portfolio/work-08.jpg','/portfolio/work-09.jpg','/portfolio/work-10.jpg'];

function Navbar() {
  const [open, setOpen] = useState(false);
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/5 bg-[#0B0B0F]/75 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
    <a href="#top" className="group flex items-center" aria-label="Johnny Cutz Barbershop — início"><img src="/johnny-cutz-logo.png" alt="Johnny Cutz Barbershop" className="h-14 w-36 object-contain object-left drop-shadow-[0_0_14px_rgba(21,156,255,.18)] sm:w-44"/></a>
    <nav className="hidden items-center gap-8 text-sm text-white/60 md:flex" aria-label="Navegação principal"><a href="#servicos">Serviços</a><a href="#trabalhos">Trabalhos</a><a href="#sobre">Sobre</a></nav>
    <div className="flex items-center gap-2"><a href="#agendar" className="cta hidden sm:inline-flex">Agendar corte <ArrowRight size={16}/></a><button onClick={()=>setOpen(!open)} className="grid size-11 place-items-center rounded-full border border-white/10 md:hidden" aria-label="Abrir menu">{open?<X/>:<Menu/>}</button></div>
  </div>{open&&<nav className="border-t border-white/10 bg-[#12121A]/95 p-5 backdrop-blur-xl md:hidden"><div className="flex flex-col gap-5 text-lg"><a onClick={()=>setOpen(false)} href="#servicos">Serviços</a><a onClick={()=>setOpen(false)} href="#trabalhos">Trabalhos</a><a onClick={()=>setOpen(false)} href="#sobre">Sobre</a><a onClick={()=>setOpen(false)} href="#agendar" className="cta justify-center">Agendar corte</a></div></nav>}</header>;
}

function HeroSection() {
  return <section id="top" className="relative overflow-hidden pb-16 pt-32 lg:pb-28 lg:pt-44"><div className="noise absolute inset-0 opacity-30"/><div className="absolute -left-40 top-20 size-[32rem] rounded-full bg-[#159CFF]/10 blur-[120px]"/><div className="relative mx-auto grid max-w-7xl items-end gap-14 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8">
    <div className="reveal"><div className="eyebrow mb-7"><Sparkles size={14}/> Fresh cuts • Dreadlocks</div><h1 className="max-w-xl text-[clamp(3.5rem,8vw,7.5rem)] font-black uppercase leading-[.82] tracking-[-.07em]">Cortes<br/><span className="text-outline">precisos.</span><br/>Locks<br/><span className="text-[#159CFF]">autênticos.</span></h1><p className="mt-8 max-w-md text-base leading-7 text-white/55 sm:text-lg">Identidade, técnica e detalhe em cada sessão. Do fade mais limpo à manutenção completa das tuas locks.</p><div className="mt-9 flex flex-wrap items-center gap-4"><a className="cta" href="#agendar">Reservar sessão <ArrowDownRight size={18}/></a><a className="ghost-button" href="#trabalhos"><Camera size={17}/> Ver trabalhos</a></div></div>
    <div className="grid h-[500px] grid-cols-5 grid-rows-5 gap-3 sm:h-[650px]"><figure className="image-card col-span-3 row-span-5"><img src={images[0]} alt="Trabalho recente de Fade & Locks by Johnny"/><span className="image-tag">Fresh work</span></figure><figure className="image-card col-span-2 row-span-3"><img src={images[1]} alt="Corte realizado por Johnny"/></figure><div className="col-span-2 row-span-2 flex flex-col justify-between rounded-3xl border border-white/10 bg-[#15151D] p-5 sm:p-7"><span className="grid size-11 place-items-center rounded-full bg-[#FFE500] text-black"><Star size={19} fill="currentColor"/></span><div><p className="text-3xl font-black sm:text-5xl">1.2K</p><p className="mt-1 text-xs uppercase tracking-[.2em] text-white/40">Na comunidade</p></div></div></div>
  </div></section>;
}

function BentoServices() {
  return <section id="servicos" className="section-shell"><div className="section-head"><div><p className="eyebrow">O menu</p><h2>Serviços que falam<br/>por si.</h2></div><p>Da manutenção de locks ao freestyle: técnica, textura e um acabamento desenhado à tua medida.</p></div><div className="grid gap-4 lg:grid-cols-12">
    <article className="bento-card relative overflow-hidden lg:col-span-7 lg:row-span-2"><div className="absolute right-0 top-0 size-52 rounded-full bg-[#159CFF]/10 blur-3xl"/><div className="relative flex h-full flex-col justify-between gap-12"><div><span className="service-number">01</span><h3>Fresh Cuts<br/>& Fades</h3><p>Linhas limpas, transições suaves e acabamento preciso — desenhado à medida do teu rosto.</p></div><div className="divide-y divide-white/10 border-y border-white/10">{[['Skin fade','20€'],['Corte + barba','28€'],['Design / freestyle','25€']].map(([name,price])=><div key={name} className="flex items-center justify-between py-4"><span className="text-white/70">{name}</span><strong>{price}</strong></div>)}</div></div></article>
    <article className="bento-card bg-[#159CFF] text-[#0B0B0F] lg:col-span-5"><span className="service-number border-black/20 text-black/60">02</span><div className="mt-16"><h3>Dreadlocks<br/>& manutenção</h3><p className="!text-black/65">Retwist, styling e locks detox com técnica especializada e respeito pelo ciclo natural das locks.</p><a href="#agendar" className="mt-7 inline-flex items-center gap-2 font-bold">Ver disponibilidade <ArrowRight size={18}/></a></div></article>
    <article className="bento-card flex items-center justify-between lg:col-span-5"><div><p className="text-xs uppercase tracking-[.2em] text-white/40">Tempo médio</p><p className="mt-4 text-5xl font-black">45<span className="text-[#159CFF]">min</span></p><p className="mt-2 text-sm text-white/45">Corte & acabamento</p></div><Clock3 className="text-[#159CFF]" size={64} strokeWidth={1}/></article>
  </div></section>;
}

function InstagramFeed() {
  return <section id="trabalhos" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="section-head"><div><p className="eyebrow">@johnny_cutzznlocks</p><h2>Feito no chair.<br/>Visto no feed.</h2></div><a className="ghost-button" href={INSTAGRAM} target="_blank" rel="noreferrer"><Camera size={17}/> Seguir no Instagram</a></div></div><div className="no-scrollbar flex snap-x gap-3 overflow-x-auto px-[max(1.25rem,calc((100vw-80rem)/2))] pb-4">{images.map((src,i)=><a key={src} href={INSTAGRAM} target="_blank" rel="noreferrer" className="feed-card group"><img src={src} alt={`Trabalho Fade & Locks ${i+1}`}/><span className="feed-overlay"><span><Star size={18} fill="currentColor"/> {84+i*13}</span><span><MessageCircle size={18} fill="currentColor"/> {6+i}</span></span></a>)}</div></section>;
}

const dates=[{day:'Ter',date:25},{day:'Qua',date:26},{day:'Qui',date:27},{day:'Sex',date:28},{day:'Sáb',date:29}];
const slots=['09:30','11:00','14:00','15:30','17:00','18:30'];

function BookingWidget() {
  const [date,setDate]=useState(26); const [time,setTime]=useState('14:00'); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [done,setDone]=useState(false); const summary=useMemo(()=>`${date} Ago • ${time}`,[date,time]);
  function submit(e:React.FormEvent){e.preventDefault();if(name&&phone)setDone(true)}
  return <section id="agendar" className="section-shell pb-28"><div className="rounded-[2rem] border border-white/10 bg-[#12121A] p-5 sm:p-8 lg:p-12"><div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Reserva online</p><h2 className="mt-5">O teu próximo<br/>look começa aqui.</h2></div><a href="https://www.google.com/maps/search/?api=1&query=Av.+de+Santa+Maria+18A" target="_blank" rel="noreferrer" className="flex items-center gap-3 text-sm text-white/50 hover:text-white"><MapPin size={18} className="text-[#159CFF]"/> Av. de Santa Maria 18A</a></div>
  {done?<div className="grid min-h-[360px] place-items-center rounded-3xl border border-[#159CFF]/30 bg-[#159CFF]/5 p-8 text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-[#FFE500] text-black"><Check size={30}/></span><h3 className="mt-6 text-3xl font-black">Pedido recebido, {name.split(' ')[0]}!</h3><p className="mx-auto mt-3 max-w-md text-white/50">A tua sessão para <strong className="text-white">{summary}</strong> ficou pré-reservada. Vais receber a confirmação por contacto.</p><button onClick={()=>setDone(false)} className="ghost-button mt-7">Nova reserva</button></div></div>:<form onSubmit={submit} className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl bg-[#0B0B0F] p-5 sm:p-7"><div className="flex items-center justify-between"><button type="button" aria-label="Mês anterior" className="calendar-arrow"><ChevronLeft size={18}/></button><div className="text-center"><p className="font-bold">Agosto 2026</p><p className="text-xs text-white/35">Escolhe o melhor dia</p></div><button type="button" aria-label="Mês seguinte" className="calendar-arrow"><ChevronRight size={18}/></button></div><div className="mt-7 grid grid-cols-5 gap-2">{dates.map(d=><button type="button" onClick={()=>setDate(d.date)} key={d.date} className={`date-button ${date===d.date?'active':''}`}><span>{d.day}</span><strong>{d.date}</strong></button>)}</div><p className="mb-3 mt-8 text-xs font-bold uppercase tracking-[.18em] text-white/40">Horários disponíveis</p><div className="grid grid-cols-3 gap-2">{slots.map(s=><button type="button" onClick={()=>setTime(s)} key={s} className={`time-button ${time===s?'active':''}`}>{s}</button>)}</div></div><div className="flex flex-col rounded-3xl border border-white/10 p-5 sm:p-7"><div><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#159CFF]/15 text-[#159CFF]"><CalendarDays size={19}/></span><div><p className="text-xs uppercase tracking-[.16em] text-white/35">A tua sessão</p><p className="font-bold">{summary}</p></div></div><label className="form-label mt-7">Nome<input required value={name} onChange={e=>setName(e.target.value)} placeholder="O teu nome"/></label><label className="form-label mt-4">Telemóvel<input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+351 9xx xxx xxx"/></label><label className="form-label mt-4">Serviço<select defaultValue="Fresh Cut & Fade"><option>Fresh Cut & Fade</option><option>Corte + Barba</option><option>Dreadlocks & Manutenção</option></select></label></div><button className="cta mt-7 w-full justify-center" type="submit">Confirmar pedido <ArrowRight size={18}/></button></div></form>}</div></section>;
}

function Footer(){return <footer id="sobre" className="border-t border-white/10"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 md:grid-cols-[1fr_auto_auto] md:items-end lg:px-8"><div><img src="/johnny-cutz-logo.png" alt="Johnny Cutz Barbershop" className="h-20 w-52 object-contain object-left"/><p className="mt-2 text-sm text-white/35">Fresh cuts & dreadlocks.</p></div><div className="space-y-3 text-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-white/30">Contacto</p><a href="tel:+351964443476" className="flex items-center gap-2 text-white/70 hover:text-[#FFE500]"><Phone size={17}/> 964 443 476</a><a href="https://www.google.com/maps/search/?api=1&query=Av.+de+Santa+Maria+18A" target="_blank" rel="noreferrer" className="flex items-center gap-2 text-white/70 hover:text-[#159CFF]"><MapPin size={17}/> Av. de Santa Maria 18A</a></div><div className="flex items-center gap-5 text-sm text-white/45"><a href="#servicos">Serviços</a><a href="#agendar">Agendar</a><a href={INSTAGRAM} target="_blank" rel="noreferrer" aria-label="Instagram"><Camera size={20}/></a></div></div></footer>}

export default function Home(){return <main><Navbar/><HeroSection/><BentoServices/><InstagramFeed/><BookingWidget/><Footer/></main>}
